permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 孙雪
  email: 1009038656@qq.com
  github: http://github.com/sunxue

# 站点信息
title: 孙雪的博客 
description: 孙雪的博客
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /_includes/image.jpg
favicon: /_includes/image.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
#  url: yansu.org

#disqus 设置
disqus:
  shortname: suyan-zh